import "./globals.css";
import type { Metadata } from "next";
import { Funnel_Display } from "next/font/google";

const funnelDisplay = Funnel_Display({
  variable: "--font-funnel_display",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${funnelDisplay.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
